const supertest = require("supertest")
const app=require("../src/app.js")
const taskService=require("../src/services/taskService.js")
const req=supertest;
beforeEach(()=>{
    taskService._reset();
})
test("create a task via post and return  of status 201",async ()=>{
    const res=await req(app)
    .post('/tasks')
    .send({title: 'Buy Car'})
    expect(res.status).toBe(201)
    expect(res.body.title).toBe('Buy Car')
})
test("Cheking weather the tasks are getting fully updated",async ()=>{
    const res1=await req(app)
    .post('/tasks')
    .send({title: 'Buy Laptop'})
    const res2=await req(app)
    .put("/tasks/"+res1.body.id)
    .send({description:"Buying a Laptop at cheap price"})
    expect(res2.body.description).toBe("Buying a Laptop at cheap price")
})
test("Checking weather it deletes task succesfully or not",async ()=>{
   const res1=await req(app)
    .post('/tasks')
    .send({title: 'Buy House'})
    const res2=await req(app)
    .delete("/tasks/"+res1.body.id)
    const t1=taskService.findById(res1.body.id)
    expect(t1).toBeUndefined();
})
test("Checking weather the task gets marked completed or not",async ()=>{
    const res1=await req(app)
    .post('/tasks')
    .send({title: 'Buy Farm'})
    const res2=await req(app)
    .patch("/tasks/"+res1.body.id+"/complete")
    expect(res2.body.status).toBe('done')
})
test("Checking weather the task gets assigned to user or not",async()=>{
     const res1=await req(app)
    .post('/tasks')
    .send({title: 'Sell Farm'})
    const res2=await req(app)
    .patch("/tasks/"+res1.body.id+"/assign")
    .send({assignedUsername:'alex'})
    expect(res2.body.assignee).toBe('alex')
})
test("checking weather it is listing all the tasks or not ",async ()=>{
     const res1=await req(app)
    .post('/tasks')
    .send({title: 'Sell Farm'})
    const res2=await req(app)
    .post('/tasks')
    .send({title: 'Buy Farm'})
    const res3=await req(app)
    .post('/tasks')
    .send({title: 'Buy House'})
    const res4=await req(app)
    .get("/tasks?"+"page="+1+"&limit="+10)
    expect(res4.body).toHaveLength(3)
})
test("testing weather it is returning it is counting by stats and overdues thing or not ",async ()=>{
     const res1=await req(app)
    .post('/tasks')
    .send({title: 'Sell Farm'})
    const res2=await req(app)
    .post('/tasks')
    .send({title: 'Buy Farm'})
    const res3=await req(app)
    .post('/tasks')
    .send({title: 'Buy House'})
    const res4=await req(app)
    .get("/tasks/stats")
    expect(res4.body.todo).toBe(3)
})